### ISSUE TITLE
add_element_to_end_of_list() test wont pass

### ISSUE THREAD

**Issue by WAB0003** [learn-co-curriculum/python-p3-list-crud-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236189?module_item_id=554054

### Concern

having an issue getting **add_element_to_end_of_list()** test to pass. I've looked at the test file and checked results on a python REPL to confirm i'm getting the correct answer.

def add_element_to_end_of_list(l, element):
    return list(l).append(element)

For some reason the test says this is not a list and the last element is not there?

**Comment by PaNDa2code** [comment]
try:

`def add_element_to_end_of_list(l, element):`
`    l.append(element)`
`    return l`


or:

`def add_element_to_end_of_list(l, element):`
`    liSt = l.append(element)`
`    return liSt`

or:
`def add_element_to_end_of_list(l, element):`
`    return l + [element]`


good luck :)

**Comment by professor-ben** [comment]
Hi Bill,

`append()` modifies a list, but does not return a list. You will need to return the modified list like Batman showed above.

Thanks,
Ben
